const livros = [
    {
        id: "genesis",
        imagem: "https://th.bing.com/th/id/R.da65f11890bb8ae14e1a630752a43f8e?rik=D%2bZElK0XYMTEsg&pid=ImgRaw&r=0",
        titulo: "Gênesis",
        descricao: "Primeiro livro da Bíblia escrito por Moisés, que narra o início da criação e da humanidade.",
        autor: "Moisés",
        ano: "aproximadamente 4000 a.C.",
        versiculo: 1533,
        capitulo: 50,
        contexto_historico: "Relata a criação do mundo, a queda do homem, o dilúvio e a história dos patriarcas até a ascensão de José no Egito."
    },
    {
        id: "exodo",
        imagem: "https://th.bing.com/th/id/OIP.72dnOO_BCcsNlMk0QV1FewHaFj?rs=1&pid=ImgDetMain",
        titulo: "Êxodo",
        descricao: "Segundo livro da Bíblia, escrito por Moisés, que narra a libertação do povo de Israel da escravidão no Egito.",
        autor: "Moisés",
        ano: "aproximadamente 1445 a.C.",
        versiculo: 1213,
        capitulo: 40,
        contexto_historico: "Descreve a saída dos israelitas do Egito e a entrega da Lei no Monte Sinai."
    },
    {
        id: "levitico",
        imagem: "https://th.bing.com/th/id/OIP.N1euN2CE7TYwUDZIw5K5yQAAAA?rs=1&pid=ImgDetMain",
        titulo: "Levítico",
        descricao: "Terceiro livro da Bíblia, escrito por Moisés, que contém as leis e regulamentos para o povo de Israel.",
        autor: "Moisés",
        ano: "aproximadamente 1445 a.C.",
        versiculo: 859,
        capitulo: 27,
        contexto_historico: "Fornece leis sobre o culto a Deus, as ofertas e os rituais de purificação."
    },
    {
        id: "numeros",
        imagem: "https://th.bing.com/th/id/OIP.hlEJYCJZhqyEUFKSOGzlLQHaE8?w=1200&h=800&rs=1&pid=ImgDetMain",
        titulo: "Números",
        descricao: "Quarto livro da Bíblia, escrito por Moisés, que relata as viagens do povo de Israel pelo deserto.",
        autor: "Moisés",
        ano: "aproximadamente 1406 a.C.",
        versiculo: 1288,
        capitulo: 36,
        contexto_historico: "Faz o censo do povo e relata os eventos durante a peregrinação no deserto até a Terra Prometida."
    },
    {
        id: "deuteronomio",
        imagem: "https://th.bing.com/th/id/OIP.cD3BU6ypU1qCI_9akNuOmgHaFj?rs=1&pid=ImgDetMain",
        titulo: "Deuteronômio",
        descricao: "Quinto livro da Bíblia, escrito por Moisés, que contém discursos e leis reforçando a aliança de Deus com Israel.",
        autor: "Moisés",
        ano: "aproximadamente 1406 a.C.",
        versiculo: 959,
        capitulo: 34,
        contexto_historico: "Reafirma a Lei de Deus antes de entrar na Terra Prometida e a morte de Moisés."
    },
    {
        id: "josue",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Josué",
        descricao: "Sexto livro da Bíblia, escrito por Josué, que narra a conquista e divisão da Terra Prometida.",
        autor: "Josué",
        ano: "aproximadamente 1370 a.C.",
        versiculo: 658,
        capitulo: 24,
        contexto_historico: "Descreve a liderança de Josué e a tomada de Canaã pelos israelitas."
    },
    {
        id: "juizes",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Juízes",
        descricao: "Sétimo livro da Bíblia, escrito por diversos autores, que narra a história dos juízes de Israel e a transição para a monarquia.",
        autor: "Diversos autores",
        ano: "aproximadamente 1050 a.C.",
        versiculo: 618,
        capitulo: 21,
        contexto_historico: "Fala sobre os períodos de opressão e libertação do povo de Israel sob os juízes."
    },
    {
        id: "rute",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Rute",
        descricao: "Oitavo livro da Bíblia, escrito por um autor anônimo, que narra a história de Rute, uma mulher moabita que se torna parte do povo de Israel.",
        autor: "Anônimo",
        ano: "aproximadamente 1100 a.C.",
        versiculo: 85,
        capitulo: 4,
        contexto_historico: "Relata a fidelidade de Rute e sua inclusão na linhagem do rei Davi."
    },
    {
        id: "1samuel",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "1 Samuel",
        descricao: "Nono livro da Bíblia, escrito por diversos autores, que narra a transição de Israel de uma teocracia para uma monarquia.",
        autor: "Diversos autores",
        ano: "aproximadamente 1050 a.C.",
        versiculo: 810,
        capitulo: 31,
        contexto_historico: "Descreve a vida do profeta Samuel, a unção de Saul como o primeiro rei de Israel e a ascensão de Davi."
    },
    {
        id: "2samuel",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "2 Samuel",
        descricao: "Décimo livro da Bíblia, escrito por diversos autores, que continua a história de Davi como rei de Israel.",
        autor: "Diversos autores",
        ano: "aproximadamente 970 a.C.",
        versiculo: 695,
        capitulo: 24,
        contexto_historico: "Relata o reinado de Davi, suas vitórias, seus pecados e as consequências de suas ações."
    },
    {
        id: "1reis",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "1 Reis",
        descricao: "Décimo primeiro livro da Bíblia, escrito por diversos autores, que descreve o reinado de Salomão e a divisão do reino de Israel.",
        autor: "Diversos autores",
        ano: "aproximadamente 900 a.C.",
        versiculo: 816,
        capitulo: 22,
        contexto_historico: "Descreve a ascensão de Salomão, a construção do Templo e a divisão do reino após sua morte."
    },
    {
        id: "2reis",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "2 Reis",
        descricao: "Décimo segundo livro da Bíblia, escrito por diversos autores, que relata a história do reino de Israel até o exílio babilônico.",
        autor: "Diversos autores",
        ano: "aproximadamente 586 a.C.",
        versiculo: 719,
        capitulo: 25,
        contexto_historico: "Fala sobre a queda de Israel e Judá e o exílio do povo de Israel."
    },
    {
        id: "1cronicas",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "1 Crônicas",
        descricao: "Décimo terceiro livro da Bíblia, escrito por Esdras, que revisita a história de Israel, destacando o reinado de Davi.",
        autor: "Esdras",
        ano: "aproximadamente 450 a.C.",
        versiculo: 942,
        capitulo: 29,
        contexto_historico: "Reconta a história de Israel com ênfase no reinado de Davi e nos preparativos para a construção do Templo."
    },
    {
        id: "2cronicas",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "2 Crônicas",
        descricao: "Décimo quarto livro da Bíblia, escrito por Esdras, que continua a história de Israel, focando no reinado de Salomão até a queda de Judá.",
        autor: "Esdras",
        ano: "aproximadamente 430 a.C.",
        versiculo: 822,
        capitulo: 36,
        contexto_historico: "Descreve a história dos reis de Judá e a destruição de Jerusalém."
    },
    {
        id: "esdras",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Esdras",
        descricao: "Décimo quinto livro da Bíblia, escrito por Esdras, que narra o retorno dos judeus do exílio babilônico e a reconstrução do Templo.",
        autor: "Esdras",
        ano: "aproximadamente 450 a.C.",
        versiculo: 280,
        capitulo: 10,
        contexto_historico: "Relata o retorno dos exilados e a restauração do culto e da adoração a Deus."
    },
    {
        id: "neemias",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Neemias",
        descricao: "Décimo sexto livro da Bíblia, escrito por Neemias, que relata a reconstrução dos muros de Jerusalém e a reforma religiosa.",
        autor: "Neemias",
        ano: "aproximadamente 445 a.C.",
        versiculo: 406,
        capitulo: 13,
        contexto_historico: "Fala sobre o trabalho de Neemias para reconstruir os muros de Jerusalém e restaurar o culto a Deus."
    },
    {
        id: "ester",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Ester",
        descricao: "Décimo sétimo livro da Bíblia, escrito por Mordecai e Ester, que narra como Ester salvou o povo judeu da destruição.",
        autor: "Mordecai e Ester",
        ano: "aproximadamente 465 a.C.",
        versiculo: 167,
        capitulo: 10,
        contexto_historico: "Relata a história de Ester e sua coragem ao interceder pelo povo judeu diante do rei persa."
    },
    {
        id: "jo",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Jó",
        descricao: "Décimo oitavo livro da Bíblia, escrito por um autor anônimo, que trata do sofrimento de Jó e da soberania de Deus.",
        autor: "Anônimo",
        ano: "aproximadamente 2000 a.C.",
        versiculo: 1070,
        capitulo: 42,
        contexto_historico: "Fala sobre o sofrimento de Jó, sua fé em Deus e os diálogos com seus amigos sobre o sofrimento humano."
    },
    {
        id: "salmos",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Salmos",
        descricao: "Décimo nono livro da Bíblia, uma coleção de cânticos, orações e poesias, muitos escritos por Davi.",
        autor: "Diversos autores, incluindo Davi",
        ano: "aproximadamente 1000 a.C.",
        versiculo: 150,
        capitulo: 150,
        contexto_historico: "É um livro de louvor, adoração, arrependimento e pedido de ajuda a Deus, com muitos salmos atribuídos a Davi."
    },
    {
        id: "provérbios",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Provérbios",
        descricao: "Vigésimo livro da Bíblia, escrito principalmente por Salomão, contendo sabedoria prática sobre a vida.",
        autor: "Salomão",
        ano: "aproximadamente 950 a.C.",
        versiculo: 915,
        capitulo: 31,
        contexto_historico: "Oferece conselhos sobre moralidade, comportamento e sabedoria."
    },
    {
        id: "ecclesiastes",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Eclesiastes",
        descricao: "Vigésimo primeiro livro da Bíblia, escrito por Salomão, que reflete sobre o sentido da vida e a futilidade das coisas terrenas.",
        autor: "Salomão",
        ano: "aproximadamente 935 a.C.",
        versiculo: 222,
        capitulo: 12,
        contexto_historico: "Explora a busca de significado e a vanidade das realizações humanas."
    },
    {
        id: "cantares",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Cantares",
        descricao: "Vigésimo segundo livro da Bíblia, escrito por Salomão, que é um poema de amor e celebração entre o noivo e a noiva.",
        autor: "Salomão",
        ano: "aproximadamente 950 a.C.",
        versiculo: 117,
        capitulo: 8,
        contexto_historico: "É um poema alegórico de amor, muitas vezes interpretado como símbolo do relacionamento de Deus com seu povo."
    },
    {
        id: "isaías",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Isaías",
        descricao: "Livro do Antigo Testamento, escrito por Isaías, que contém mensagens de julgamento e esperança para Israel e as nações.",
        autor: "Isaías",
        ano: "aproximadamente 740 a.C.",
        versiculo: 1292,
        capitulo: 66,
        contexto_historico: "Profetiza sobre a vinda do Messias, o juízo de Deus contra as nações e o futuro de Israel."
    },
    {
        id: "jeremias",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Jeremias",
        descricao: "Livro do Antigo Testamento, escrito por Jeremias, que descreve o ministério do profeta durante a queda de Jerusalém e o exílio babilônico.",
        autor: "Jeremias",
        ano: "aproximadamente 627 a.C. - 586 a.C.",
        versiculo: 1364,
        capitulo: 52,
        contexto_historico: "Relata a advertência de Jeremias sobre o julgamento de Deus, a destruição de Jerusalém e a promessa de restauração."
    },
    {
        id: "lamentacoes",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Lamentações",
        descricao: "Livro do Antigo Testamento, tradicionalmente atribuído a Jeremias, que expressa o lamento pela destruição de Jerusalém.",
        autor: "Jeremias",
        ano: "aproximadamente 586 a.C.",
        versiculo: 154,
        capitulo: 5,
        contexto_historico: "Lamentações poéticas que refletem o sofrimento do povo de Israel após a queda de Jerusalém."
    },
    {
        id: "ezequiel",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Ezequiel",
        descricao: "Livro do Antigo Testamento, escrito pelo profeta Ezequiel, que descreve suas visões e profecias durante o exílio babilônico.",
        autor: "Ezequiel",
        ano: "aproximadamente 593 a.C. - 571 a.C.",
        versiculo: 1273,
        capitulo: 48,
        contexto_historico: "Contém profecias de julgamento, restauração e uma visão detalhada de um futuro templo em Jerusalém."
    },
    {
        id: "daniel",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Daniel",
        descricao: "Livro do Antigo Testamento, escrito por Daniel, que narra a história de Daniel e seus amigos no exílio babilônico e suas visões apocalípticas.",
        autor: "Daniel",
        ano: "aproximadamente 605 a.C. - 536 a.C.",
        versiculo: 1212,
        capitulo: 12,
        contexto_historico: "Relata eventos significativos durante o exílio babilônico, incluindo as visões proféticas de Daniel sobre os reinos futuros."
    },
    {
        id: "oseias",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Oséias",
        descricao: "Livro do Antigo Testamento, escrito por Oséias, que retrata o relacionamento de Deus com Israel, comparado a um casamento infiel.",
        autor: "Oséias",
        ano: "aproximadamente 755 a.C. - 710 a.C.",
        versiculo: 197,
        capitulo: 14,
        contexto_historico: "Descreve a infidelidade de Israel a Deus e as consequências, mas também promete restauração e amor de Deus."
    },
    {
        id: "joel",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Joel",
        descricao: "Livro do Antigo Testamento, escrito por Joel, que profetiza sobre o juízo de Deus, mas também sobre a promessa do derramamento do Espírito Santo.",
        autor: "Joel",
        ano: "aproximadamente 835 a.C.",
        versiculo: 73,
        capitulo: 3,
        contexto_historico: "Fala sobre o juízo de Deus sobre as nações e a promessa de restauração através do derramamento do Espírito."
    },
    {
        id: "amós",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Amós",
        descricao: "Livro do Antigo Testamento, escrito por Amós, que traz uma mensagem de julgamento contra a injustiça social e a adoração falsa em Israel.",
        autor: "Amós",
        ano: "aproximadamente 760 a.C.",
        versiculo: 146,
        capitulo: 9,
        contexto_historico: "Foca no juízo de Deus sobre as nações ao redor de Israel e sobre o próprio Israel, devido à corrupção moral e religiosa."
    },
    {
        id: "obadias",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Obadias",
        descricao: "Livro do Antigo Testamento, escrito por Obadias, que profetiza o juízo contra Edom, inimigo de Israel, e a restauração de Israel.",
        autor: "Obadias",
        ano: "aproximadamente 586 a.C.",
        versiculo: 21,
        capitulo: 1,
        contexto_historico: "A mensagem de Obadias é uma profecia contra Edom pela sua hostilidade a Israel e uma promessa de restauração para o povo de Deus."
    },
    {
        id: "jonas",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Jonas",
        descricao: "Livro do Antigo Testamento, escrito por Jonas, que conta a história do profeta que foi enviado por Deus para pregar arrependimento em Nínive.",
        autor: "Jonas",
        ano: "aproximadamente 780 a.C.",
        versiculo: 48,
        capitulo: 4,
        contexto_historico: "Jonas é enviado para a cidade de Nínive para pregar a conversão, mas enfrenta dificuldades ao obedecer a Deus."
    },
    {
        id: "miqueias",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Miquéias",
        descricao: "Livro do Antigo Testamento, escrito por Miquéias, que traz uma mensagem de julgamento sobre as injustiças de Israel e Judá, mas também de esperança.",
        autor: "Miquéias",
        ano: "aproximadamente 740 a.C. - 700 a.C.",
        versiculo: 105,
        capitulo: 7,
        contexto_historico: "Denuncia a corrupção das lideranças e promete a vinda de um rei justo da linhagem de Davi."
    },
    {
        id: "naum",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Naum",
        descricao: "Livro do Antigo Testamento, escrito por Naum, que profetiza a queda de Nínive, a capital do Império Assírio.",
        autor: "Naum",
        ano: "aproximadamente 650 a.C.",
        versiculo: 47,
        capitulo: 3,
        contexto_historico: "Profetiza sobre o juízo de Deus sobre a cidade de Nínive devido à sua crueldade e impiedade."
    },
    {
        id: "habacuque",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Habacuque",
        descricao: "Livro do Antigo Testamento, escrito por Habacuque, que questiona Deus sobre o sofrimento e recebe respostas sobre o juízo divino.",
        autor: "Habacuque",
        ano: "aproximadamente 610 a.C.",
        versiculo: 56,
        capitulo: 3,
        contexto_historico: "Habacuque questiona a aparente prosperidade dos ímpios e recebe a resposta de que o justo viverá pela fé."
    },
    {
        id: "sofonias",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Sofonias",
        descricao: "Livro do Antigo Testamento, escrito por Sofonias, que traz uma mensagem de juízo sobre Judá e as nações, mas também de esperança para os justos.",
        autor: "Sofonias",
        ano: "aproximadamente 630 a.C.",
        versiculo: 53,
        capitulo: 3,
        contexto_historico: "Fala sobre o juízo iminente sobre Judá e as nações e a promessa de restauração para o remanescente fiel."
    },
    {
        id: "ageu",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Ageu",
        descricao: "Livro do Antigo Testamento, escrito por Ageu, que incentiva a reconstrução do Templo após o retorno do exílio babilônico.",
        autor: "Ageu",
        ano: "aproximadamente 520 a.C.",
        versiculo: 38,
        capitulo: 2,
        contexto_historico: "Ageu encoraja o povo de Israel a retomar a reconstrução do Templo, prometendo a presença de Deus entre eles."
    },
    {
        id: "zacarias",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Zacarias",
        descricao: "Livro do Antigo Testamento, escrito por Zacarias, que contém visões apocalípticas e encorajamento para a reconstrução do Templo.",
        autor: "Zacarias",
        ano: "aproximadamente 520 a.C.",
        versiculo: 211,
        capitulo: 14,
        contexto_historico: "Zacarias motiva os judeus a concluir a reconstrução do Templo e faz profecias sobre o Messias e o futuro de Jerusalém."
    },
    {
        id: "malaquias",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Malaquias",
        descricao: "Último livro do Antigo Testamento, escrito por Malaquias, que denuncia a corrupção e o abandono da verdadeira adoração a Deus.",
        autor: "Malaquias",
        ano: "aproximadamente 430 a.C.",
        versiculo: 55,
        capitulo: 4,
        contexto_historico: "Malaquias confronta o povo e os sacerdotes por suas falhas espirituais e aponta a vinda de um mensageiro do Senhor."
    },
    {
        id: "mateus",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Mateus",
        descricao: "Primeiro livro do Novo Testamento, escrito por Mateus, que descreve a vida, ministério, morte e ressurreição de Jesus Cristo.",
        autor: "Mateus",
        ano: "aproximadamente 60 d.C.",
        versiculo: 1071,
        capitulo: 28,
        contexto_historico: "Mateus escreve para os judeus, enfatizando que Jesus é o Messias prometido no Antigo Testamento."
    },
    {
        id: "marcos",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Marcos",
        descricao: "Segundo livro do Novo Testamento, escrito por Marcos, que narra de forma concisa a vida e os feitos de Jesus.",
        autor: "Marcos",
        ano: "aproximadamente 60 d.C.",
        versiculo: 678,
        capitulo: 16,
        contexto_historico: "Marcos escreve para os cristãos gentios, destacando a ação de Jesus e seu sacrifício redentor."
    },
    {
        id: "lucas",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Lucas",
        descricao: "Terceiro livro do Novo Testamento, escrito por Lucas, que oferece uma narrativa detalhada da vida de Jesus e a história inicial da Igreja.",
        autor: "Lucas",
        ano: "aproximadamente 60 d.C.",
        versiculo: 1151,
        capitulo: 24,
        contexto_historico: "Lucas escreve para os gentios, buscando dar uma visão detalhada e organizada sobre os feitos de Jesus."
    },
    {
        id: "joao",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "João",
        descricao: "Quarto livro do Novo Testamento, escrito por João, que se concentra na divindade de Jesus e na vida eterna.",
        autor: "João",
        ano: "aproximadamente 90 d.C.",
        versiculo: 879,
        capitulo: 21,
        contexto_historico: "João escreve para os cristãos, enfatizando a identidade de Jesus como Filho de Deus e a sua missão de salvar o mundo."
    },
    {
        id: "atos",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Atos dos Apóstolos",
        descricao: "Livro do Novo Testamento que narra a história dos primeiros cristãos e a propagação do evangelho após a ascensão de Jesus.",
        autor: "Lucas",
        ano: "aproximadamente 63 d.C.",
        versiculo: 1007,
        capitulo: 28,
        contexto_historico: "Atos descreve como o Espírito Santo capacita os apóstolos a expandirem a Igreja cristã pelo Império Romano."
    },
    {
        id: "romanos",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Romanos",
        descricao: "Epístola escrita por Paulo, explicando a doutrina da justificação pela fé e o papel da graça na salvação.",
        autor: "Paulo",
        ano: "aproximadamente 57 d.C.",
        versiculo: 433,
        capitulo: 16,
        contexto_historico: "Romanos aborda temas centrais da fé cristã, como a justificação pela fé, a santificação e a vida em Cristo."
    },
    {
        id: "1corintios",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "1 Coríntios",
        descricao: "Epístola de Paulo à Igreja em Corinto, tratando de questões práticas e doutrinárias dentro da comunidade cristã.",
        autor: "Paulo",
        ano: "aproximadamente 55 d.C.",
        versiculo: 437,
        capitulo: 16,
        contexto_historico: "Paulo escreve para corrigir divisões na Igreja de Corinto e oferecer instrução sobre a vida cristã."
    },
    {
        id: "2corintios",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "2 Coríntios",
        descricao: "Epístola de Paulo à Igreja de Corinto, onde ele defende seu apostolado e fala sobre o ministério da reconciliação.",
        autor: "Paulo",
        ano: "aproximadamente 56 d.C.",
        versiculo: 256,
        capitulo: 13,
        contexto_historico: "Paulo fala sobre seu ministério apostólico e a importância da generosidade e reconciliação na vida cristã."
    },
    {
        id: "gálatas",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Gálatas",
        descricao: "Epístola de Paulo às igrejas da Galácia, abordando a liberdade em Cristo e a luta contra a imposição da lei judaica.",
        autor: "Paulo",
        ano: "aproximadamente 48 d.C.",
        versiculo: 149,
        capitulo: 6,
        contexto_historico: "Paulo defende a justificação pela fé e refuta os ensinos judaizantes que tentavam impor a circuncisão aos gentios."
    },
    {
        id: "efesios",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Efésios",
        descricao: "Epístola de Paulo aos cristãos em Éfeso, falando sobre a unidade da Igreja e a plenitude da vida em Cristo.",
        autor: "Paulo",
        ano: "aproximadamente 60 d.C.",
        versiculo: 155,
        capitulo: 6,
        contexto_historico: "Paulo destaca a igreja como o corpo de Cristo e ensina sobre a natureza da vida cristã em comunidade."
    },
    {
        id: "filipenses",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Filipenses",
        descricao: "Epístola de Paulo à Igreja de Filipos, onde ele expressa gratidão e alegria pela colaboração no evangelho.",
        autor: "Paulo",
        ano: "aproximadamente 61 d.C.",
        versiculo: 104,
        capitulo: 4,
        contexto_historico: "Paulo escreve de forma encorajadora, falando sobre a alegria no sofrimento e a importância da humildade."
    },
    {
        id: "colossenses",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Colossenses",
        descricao: "Epístola de Paulo aos cristãos em Colossos, alertando contra falsas doutrinas e enfatizando a supremacia de Cristo.",
        autor: "Paulo",
        ano: "aproximadamente 60 d.C.",
        versiculo: 95,
        capitulo: 4,
        contexto_historico: "Paulo combate heresias que estavam infiltrando a Igreja e apresenta Cristo como o centro de toda a criação."
    },
    {
        id: "1tessaloniceses",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "1 Tessalonicenses",
        descricao: "Primeira carta de Paulo aos tessalonicenses, incentivando-os a permanecer firmes na fé e explicando sobre a segunda vinda de Cristo.",
        autor: "Paulo",
        ano: "aproximadamente 51 d.C.",
        versiculo: 89,
        capitulo: 5,
        contexto_historico: "Paulo encoraja a Igreja em Tessalônica a viver de forma digna e a esperar com esperança o retorno de Cristo."
    },
    {
        id: "2tessaloniceses",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "2 Tessalonicenses",
        descricao: "Segunda carta de Paulo aos tessalonicenses, corrigindo mal-entendidos sobre a segunda vinda de Cristo.",
        autor: "Paulo",
        ano: "aproximadamente 51-52 d.C.",
        versiculo: 47,
        capitulo: 3,
        contexto_historico: "Paulo esclarece que a segunda vinda de Cristo ainda não ocorreu e adverte contra a ociosidade."
    },
    {
        id: "1timoteo",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "1 Timóteo",
        descricao: "Epístola de Paulo a Timóteo, instruindo-o sobre a liderança na igreja e como lidar com questões doutrinárias e práticas.",
        autor: "Paulo",
        ano: "aproximadamente 63-65 d.C.",
        versiculo: 113,
        capitulo: 6,
        contexto_historico: "Paulo ensina sobre a boa conduta e as responsabilidades de um líder cristão, incluindo as qualificações para bispos e diáconos."
    },
    {
        id: "2timoteo",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "2 Timóteo",
        descricao: "Segunda carta de Paulo a Timóteo, um encorajamento final antes de sua morte, focando na fidelidade à verdade do evangelho.",
        autor: "Paulo",
        ano: "aproximadamente 67 d.C.",
        versiculo: 83,
        capitulo: 4,
        contexto_historico: "Paulo dá instruções a Timóteo para perseverar na fé e anunciar o evangelho com coragem, mesmo diante de perseguições."
    },
    {
        id: "tito",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Tito",
        descricao: "Epístola de Paulo a Tito, oferecendo conselhos sobre como liderar a Igreja em Creta e lidar com falsas doutrinas.",
        autor: "Paulo",
        ano: "aproximadamente 63-65 d.C.",
        versiculo: 46,
        capitulo: 3,
        contexto_historico: "Paulo instrui Tito a corrigir os erros doutrinários e ensinar a vida cristã prática nas comunidades de Creta."
    },
    {
        id: "filemon",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Filemom",
        descricao: "Epístola de Paulo a Filemom, intercedendo em favor de Onésimo, um escravo fugitivo, para que seja acolhido como irmão na fé.",
        autor: "Paulo",
        ano: "aproximadamente 60-61 d.C.",
        versiculo: 25,
        capitulo: 1,
        contexto_historico: "Paulo apela para a reconciliação e o perdão, abordando a relação entre escravo e senhor sob a ótica cristã."
    },
    {
        id: "hebreus",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Hebreus",
        descricao: "Epístola do Novo Testamento que enfatiza a supremacia de Cristo como o cumprimento de todas as promessas do Antigo Testamento.",
        autor: "desconhecido (possivelmente Paulo)",
        ano: "aproximadamente 67-70 d.C.",
        versiculo: 303,
        capitulo: 13,
        contexto_historico: "O livro de Hebreus argumenta que Jesus é o sumo sacerdote perfeito e superior a Moisés e aos sacerdotes do Antigo Testamento."
    },
    {
        id: "tiago",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Tiago",
        descricao: "Epístola de Tiago, enfatizando a prática da fé verdadeira através das obras e a sabedoria para viver em Cristo.",
        autor: "Tiago",
        ano: "aproximadamente 48-49 d.C.",
        versiculo: 108,
        capitulo: 5,
        contexto_historico: "Tiago ensina que a fé sem obras é morta e que os cristãos devem viver com sabedoria, humildade e em oração."
    },
    {
        id: "1pedro",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "1 Pedro",
        descricao: "Primeira carta de Pedro, oferecendo encorajamento aos cristãos perseguidos, destacando a santidade e a esperança em Cristo.",
        autor: "Pedro",
        ano: "aproximadamente 60-64 d.C.",
        versiculo: 105,
        capitulo: 5,
        contexto_historico: "Pedro exorta os cristãos a permanecerem firmes na fé e a viverem de acordo com a graça de Deus, apesar das dificuldades."
    },
    {
        id: "2pedro",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "2 Pedro",
        descricao: "Segunda carta de Pedro, alertando sobre os falsos mestres e incentivando os cristãos a crescerem na graça e no conhecimento de Cristo.",
        autor: "Pedro",
        ano: "aproximadamente 65-68 d.C.",
        versiculo: 61,
        capitulo: 3,
        contexto_historico: "Pedro alerta para a vinda de falsos ensinamentos e fala sobre o dia do Senhor e a necessidade de viver de maneira santa."
    },
    {
        id: "1joao",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "1 João",
        descricao: "Primeira carta de João, que aborda o amor de Deus, a importância de viver em comunhão com Ele e a certeza da salvação.",
        autor: "João",
        ano: "aproximadamente 85-90 d.C.",
        versiculo: 105,
        capitulo: 5,
        contexto_historico: "João enfatiza a importância do amor cristão e do discernimento contra os falsos ensinos sobre a identidade de Jesus."
    },
    {
        id: "2joao",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "2 João",
        descricao: "Segunda carta de João, advertindo contra os falsos mestres e exortando a manter a verdade do evangelho.",
        autor: "João",
        ano: "aproximadamente 85-90 d.C.",
        versiculo: 13,
        capitulo: 1,
        contexto_historico: "João exorta os cristãos a permanecerem na verdade e a não receberem aqueles que negam a verdade sobre Cristo."
    },
    {
        id: "3joao",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "3 João",
        descricao: "Terceira carta de João, incentivando a hospitalidade e o apoio aos missionários.",
        autor: "João",
        ano: "aproximadamente 85-90 d.C.",
        versiculo: 15,
        capitulo: 1,
        contexto_historico: "João encoraja a generosidade e a hospitalidade, contrastando os exemplos de Diótrefes e Demétrio."
    },
    {
        id: "judas",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Judas",
        descricao: "Epístola de Judas, alertando contra os falsos mestres e exortando os cristãos a lutar pela fé.",
        autor: "Judas",
        ano: "aproximadamente 65-80 d.C.",
        versiculo: 25,
        capitulo: 1,
        contexto_historico: "Judas adverte contra os falsos ensinamentos e exorta os cristãos a se manterem firmes na verdadeira fé."
    },
    {
        id: "apocalipse",
        imagem: "https://biblicalchronology.com/wp-content/uploads/2024/02/exploring_the_name_harlow-jpg.webp",
        titulo: "Apocalipse",
        descricao: "Último livro do Novo Testamento, escrito por João, que revela visões apocalípticas sobre o fim dos tempos, o juízo final e a vitória de Cristo.",
        autor: "João",
        ano: "aproximadamente 95-96 d.C.",
        versiculo: 404,
        capitulo: 22,
        contexto_historico: "Apocalipse descreve visões simbólicas sobre o julgamento final, a destruição de Babilônia e o estabelecimento do novo céu e da nova terra."
    }
];

export default livros;